# -*- coding: utf-8 -*-
"""Análise de Dados de Vendas .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KRcam_mCBwBeVVQvVJSBggdNFBXAlx-c

Carregamento de Dados de arquivo externo
"""

import pandas as pd
import numpy as np

# Criar DataFrame com dados hipotéticos
data = {
    "Região": ["Norte", "Norte", "Sul", "Sul", "Norte"],
    "Mês": ["Jan", "Fev", "Jan", "Fev", "Mar"],
    "Vendas": [1500, np.nan, 2200, 1800, 2000],
    "Despesas": [300, 250, np.nan, 400, 350]
}

df = pd.DataFrame(data)

# Salvar em Excel
df.to_excel("vendas.xlsx", index=False, engine="openpyxl")

print("Arquivo 'vendas.xlsx' criado com sucesso!")

"""Desafio obrigatório: Análise de Dados de Vendas"""

# Importar bibliotecas necessárias
import pandas as pd
import numpy as np

# 1. Carregar e inspecionar os dados
df = pd.read_excel("vendas.xlsx")

print("* Inspeção inicial dos dados *")
print("Primeiras linhas:")
print(df.head())
print("\nValores ausentes:")
print(df.isnull().sum())

# 2. Substituir valores ausentes
print("\n* Substituição de valores ausentes *")
mediana_vendas = df['Vendas'].median()
df['Vendas'] = df['Vendas'].fillna(mediana_vendas)

media_despesas = df['Despesas'].mean()
df['Despesas'] = df['Despesas'].fillna(media_despesas)

print("\nDataFrame após substituição:")
print(df)

# 3. Agrupar dados por Região e Mês
print("\n* Agrupamento por Região e Mês *")
agrupado = df.groupby(['Região', 'Mês']).agg({
    'Vendas': 'sum',
    'Despesas': 'mean'
}).reset_index()

print(agrupado)

# 4. Combinar horizontalmente Vendas e Despesas
print("\n* Combinação horizontal *")
combinado = np.hstack((df['Vendas'].values.reshape(-1, 1),
                      df['Despesas'].values.reshape(-1, 1)))
print(combinado)

# 5. Sumário estatístico
print("\n* Sumário estatístico *")
sumario = df[['Vendas', 'Despesas']].describe(percentiles=[.5])
sumario.loc['mediana'] = df[['Vendas', 'Despesas']].median()
print(sumario)